config/routes.rb
Rails.application.routes.draw do

  get "/", to: "welcome#index", as: :root

  get "/user/new", to: "user#new", as: :new_user
  post "/user/new", to: "user#create",as: false
  get "/user/edit", to: "user#edit", as: :edit_user
  patch "/user/edit", to: "user#update", as: false
  get "/user/:id", to: "user#show", as: :show_user

  get "/login", to: "login#new", as: :new_login
  post "/login", to: "login#create", as: false
  get "/login/destroy", to: "login#destroy", as: :destroy_login

  get "/ideas", to: "ideas#index", as: :ideas
  get "/ideas/new", to: "ideas#new", as: :new_idea
  post "/ideas/new", to: "ideas#create", as: false
  get "/ideas/:id", to: "ideas#show", as: :show_idea
  get "/ideas/edit/:id", to: "ideas#edit", as: :edit_idea
  patch "/ideas/edit/:id", to: "ideas#update", as: false
  get "/ideas/destroy/:id", to: "ideas#destroy", as: :destroy_idea

  post "/ideas/:id", to: "comments#create", as: false

  get "/ideas/like/:id", to: "votations#create_like", as: :votation_like
  get "/ideas/nlike/:id", to: "votations#create_nlike", as: :votation_nlike

  get "/ideas/collaborator/new/:id", to: "collaborators#create", as: :create_collaborators
  get "/ideas/collaborator/update/:id", to: "collaborators#update", as: :update_collaborators
  get "/ideas/collaborator/delete/:id", to: "collaborators#destroy", as: :destroy_collaborators
  get "/ideas/collaborator/show", to: "collaborators#show", as: :show_collaborators

  get "/like/user/:id", to: "likes#create_like", as: :like_like
  get "/nlike/user/:id", to: "likes#create_nlike", as: :like_nlike
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  has_many :idea_comments, class_name: Comment, foreign_key: :id_idea
  has_many :votations, class_name: Votation, foreign_key: :id_idea
  has_many :idea_collaborators, class_name: Collaborator, foreign_key: :id_idea
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def index
    @ideas = Idea.all
    @like = 0
    @nlike = 0
    current_user ? @my_ideas = current_user.ideas : @my_ideas = []
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(ideas_params)
    @idea.idealizer = current_user.id

    if @idea.save
      redirect_to show_idea_path @idea
    else
      flash[:notice] = "Ouve algum erro, tente novamente mais tarde."
      render :new
    end
  end

  def show
    @settings
    @show_collaborators
    @collaborator

    @idea = Idea.find params[:id]
    @user = User.find_by_id(@idea.idealizer)
    @like = 0
    @nlike = 0
    @votations = @idea.votations
    @new_comment = Comment.new
    @comments = @idea.idea_comments
    @collaborators = @idea.idea_collaborators

    @my_ideas = current_user.ideas if current_user

  end

  def edit
    @idea = Idea.find params[:id]
  end

  def update
    @idea = Idea.find params[:id]

    @idea.update_attributes(
      params.require(:idea).permit(
        :title, 
        :idea, 
        :link, 
        :github
      )
    )

    flash[:notice] = "Editado com sucesso !"
    
    redirect_to show_idea_path(@idea.id)
  end

  def destroy
    @idea = Idea.find params[:id]
    @idea.delete
    flash[:notice] = "Excluido !"

    redirect_to ideas_path
  end

  private

  def ideas_params
    params.require(:idea).permit(
      :title, 
      :idea, 
      :idealizer, 
      :like, 
      :nlike, 
      :link, 
      :github
    )
  end

end

app/views/ideas/edit.html.erb
<%= form_for @idea, url: edit_idea_path do |edit_idea| %>
  <h1>Edit Idea</h1>
  <br>

  <%= edit_idea.text_field :title, placeholder: "Titulo" %>

  <%= edit_idea.text_area :idea, placeholder: "Ideia" %>

  <%= edit_idea.text_field :link, placeholder: "Link" %>

  <%= edit_idea.text_field :github, placeholder: "Github" %><br><br>

  <%= edit_idea.submit "Salvar edições", :class => "btn btn-primary" %>
<% end %>

app/views/ideas/index.html.erb
<div class="message_index_ideas">
  <h1>IDEIAS PARA MUDAR O MUNDO</h1>
</div>

<div id="panel_ideas" >

<% if current_user %>
<h1 id="title_index_idea">
  <%= image_tag "pen.png" %>
  Minhas Ideias
</h1>

<div class="my_ideas">

  <% @my_ideas.each do |my_ideas| %>

    <div id="ideas">
      <% @user = User.find_by_id(my_ideas.idealizer) %>
      <% @votations = my_ideas.votations %>
      <% @comments = my_ideas.idea_comments.count %>
      <% show_votations %>

      <%= image_tag @user.cover.url(:medium), id: "icon" %>
      <%= link_to "#{my_ideas.title}", show_idea_path(my_ideas.id), id: "title_idea" %>
      <div id="status_idea">
        <p><%= link_to "#{@user.name}", show_user_path(my_ideas.idealizer), id: "idealizer" %></p>
        <%= image_tag "like_icon.png", id: "icon" %> <%= @like %>
        <%= image_tag "unlike_icon.png", id: "icon" %> <%= @nlike %>
        <%= image_tag "comments_icon.png", id: "icon" %> <%= @comments %>
      </div>
      <% @description = my_ideas.idea[0..130] + " ..." %>
      <p id="description" ><%= @description %></p>
    </div>

  <% end %>

</div>

<% end %>

<h1 id="title_index_idea">
  <%= image_tag "search.png" %>
  Outras Ideias
</h1>

<div class="others_ideas">
  <% @ideas.reverse.each do |idea| %>

    <div id="ideas">
      <% @user = User.find_by_id(idea.idealizer) %>
      <% @comments = idea.idea_comments.count %>
      <% @votations = idea.votations %>
      <% show_votations %>

      <%= image_tag @user.cover.url(:medium), id: "icon" %>
      <%= link_to "#{idea.title}", show_idea_path(idea.id), id: "title_idea" %>
      <div id="status_idea">
        <p><%= link_to "#{@user.name}", show_user_path(idea.idealizer), id: "idealizer" %></p>
        <%= image_tag "like_icon.png", id: "icon" %> <%= @like %>
        <%= image_tag "unlike_icon.png", id: "icon" %> <%= @nlike %>
        <%= image_tag "comments_icon.png", id: "icon" %> <%= @comments %>
      </div>
      <% @description = idea.idea[0..130] + " ..."%>
      <p id="description"><%= @description %></p>
    </div>
  <% end %>

</div>
</div>

app/views/ideas/new.html.erb
<%= form_for @idea, url: new_idea_path do |new_idea| %>
  <h1>New Idea</h1><br><br>

  <%= new_idea.text_field :title, placeholder: "Titulo" %>

  <%= new_idea.text_area :idea, placeholder: "Ideia", style: "width: 250px; margin-bottom:-5px;" %>

  <%= new_idea.text_field :link, placeholder: "Link" %>

  <%= new_idea.text_field :github, placeholder: "Github" %><br><br>

  <%= new_idea.submit "Criar Ideia", :class => "btn btn-primary btn-more" %>
<% end %>

app/views/ideas/show.html.erb
<div id="body" style="top: 100px; padding: 60px; padding-top: 20px; z-index: 2;background-color: transparent;">

  <h1 id="user_perfil">
    <%= image_tag @user.cover.url(:medium), style: "width:125px; height:125px; border-radius: 200px; border: 2px solid rgba(0,0,0,0.5); padding: 2px; position:relative;background-color: rgb(200,200,200); float: left;" %>
    <spawn class="name_user_perfil"><%= @idea.title %></spawn>
  </h1>

  <div class="data row" style="position:relative; top: 10px;">

    <div class="col-xs-12 col-ms-4 col-md-4">
      <h3 >Ideia:</h3>
      <p><%= @idea.idea %></p>
    </div>

    <div class="col-xs-12 col-ms-4 col-md-4">
    <h3>Likes:</h3>
      <p>
        <% show_votations %>

        <%= link_to (image_tag 'like_icon.png', id: 'icon'), votation_like_path(@idea.id) %><%= @like %>
        <%= link_to (image_tag 'unlike_icon.png', id: 'icon'), votation_nlike_path(@idea.id) %><%= @nlike %>
      </p>
    </div>

    <div class="col-xs-12 col-ms-4 col-md-4">
      <h3>Idealizador:</h3>
      <p><%= link_to @user.name, show_user_path(@user.id) %></p>
    </div>

    

    <div class="col-xs-12 col-ms-4 col-md-4">
      <h3>Link:</h3>
      <p><%= link_to "#{@idea.link}", "http://#{@idea.link}", target: "_blank" %></p>
    </div>

    <div class="col-xs-12 col-ms-4 col-md-4">
      <h3>Colaboradores:</h3>
      <%= show_collaborators %>
      
      <p>    
        <% @collaborators.each do |collaborators| %>
          <% @user = User.find_by_id(collaborators.id_user) %>
          <% @approvation = collaborators %>
          <% show_approvation %>
          <%= @collaborator %><br>
        <% end %> 
      </p>
    </div>
    

    <div class="col-xs-12 col-ms-4 col-md-4">
      <h3>Configurações</h3>
      <%= show_settings %>
    </div>

    

    <div class="col-xs-12 col-ms-4 col-md-4">
      <h3>GitHub: </h3>
      <p><%= link_to "Github", "#{@idea.github}", target: "_blank"%></p>
    </div>

</div>

<div id="comments" >
  <%= form_for @new_comment , url: show_idea_path do |new_comment| %>
    <%= new_comment.label :comment, "Envie um comentario"  %><br>
    <%= new_comment.text_area :comment, style: "width: 350px; height: 100px;" %><br>

    <%= new_comment.submit "Enviar comentario", :class => "btn btn-primary btn-more" %>
  <% end %>

<% @comments.reverse.each do |comments| %>
  <div id="comment">
    <p>DE: 
      <b><%= User.find_by_id(comments.id_user).name %></b><br>
      <p><%= comments.comment %></p>
    </p>
  </div>
<% end %>
</div>
</div>