config/routes.rb
Rails.application.routes.draw do

  get "/", to: "welcome#index", as: :root

  get "/user/new", to: "user#new", as: :new_user
  post "/user/new", to: "user#create",as: false
  get "/user/edit", to: "user#edit", as: :edit_user
  patch "/user/edit", to: "user#update", as: false
  get "/user/:id", to: "user#show", as: :show_user

  get "/login", to: "login#new", as: :new_login
  post "/login", to: "login#create", as: false
  get "/login/destroy", to: "login#destroy", as: :destroy_login

  get "/ideas", to: "ideas#index", as: :ideas
  get "/ideas/new", to: "ideas#new", as: :new_idea
  post "/ideas/new", to: "ideas#create", as: false
  get "/ideas/:id", to: "ideas#show", as: :show_idea
  get "/ideas/edit/:id", to: "ideas#edit", as: :edit_idea
  patch "/ideas/edit/:id", to: "ideas#update", as: false
  get "/ideas/destroy/:id", to: "ideas#destroy", as: :destroy_idea

  post "/ideas/:id", to: "comments#create", as: false

  get "/ideas/like/:id", to: "votations#create_like", as: :votation_like
  get "/ideas/nlike/:id", to: "votations#create_nlike", as: :votation_nlike

  get "/ideas/collaborator/new/:id", to: "collaborators#create", as: :create_collaborators
  get "/ideas/collaborator/update/:id", to: "collaborators#update", as: :update_collaborators
  get "/ideas/collaborator/delete/:id", to: "collaborators#destroy", as: :destroy_collaborators
  get "/ideas/collaborator/show", to: "collaborators#show", as: :show_collaborators

  get "/like/user/:id", to: "likes#create_like", as: :like_like
  get "/nlike/user/:id", to: "likes#create_nlike", as: :like_nlike
end

app/models/user.rb
class User < ActiveRecord::Base
  
	has_secure_password

  has_many :ideas, class_name: Idea, foreign_key: :idealizer
  has_many :collaborations, class_name: Collaborator, foreign_key: :id_user
  has_many :likes , class_name: Like, foreign_key: :id_by

  has_attached_file :cover, :styles => {:medium => "300x300>"}, :default_url => "people.png"
  do_not_validate_attachment_file_type :cover

  validates_uniqueness_of :email
  validates_presence_of :name, :email

end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(users_params)

		if @user.save
			flash[:notice] = "Criado com sucesso, você já pode fazer login !"
			redirect_to root_path
		else
			flash[:notice] = "Ops, Ouve algum erro !"
			render :new
		end
	end

	def edit		
		@user = User.find_by_id(current_user.id)
	end

	def update
		@user = User.find_by_id(current_user.id)

		@user.update_attributes(
			params.require(:user).permit(
				:name, 
				:email, 
				:password, 
				:password_confirmation, 
				:cover, 
				:web, 
				:facebook, 
				:acquiriments, 
				:description
				)
		)

		flash[:notice] = "Editado com sucesso !"

		redirect_to root_path
	end

	def show
		@user = User.find params[:id]
		@likes = @user.likes
		@ideas = @user.ideas
	end

	private

	def users_params
		params.require(:user).permit(
			:name, 
			:email, 
			:password, 
			:password_confirmation, 
			:cover, 
			:like, 
			:nlike
		)
	end

end

app/views/user/edit.html.erb
<%= form_for @user, url: edit_user_path do |edit_user| %>
  <h1>Editar usuario</h1><br><br>

  <%= edit_user.text_field :name, placeholder: "Nome" %>

  <%= edit_user.text_field :email, placeholder: "E-mail" %>

  <%= edit_user.password_field :password, placeholder: "Senha" %>

  <%= edit_user.password_field :password_confirmation, placeholder: "Confirmar senha" %>

  <%= edit_user.text_area :description, placeholder: "Descrisão"  %>

  <%= edit_user.text_area :acquiriments, placeholder: "Conhecimentos" %>

  <%= edit_user.text_field :web, placeholder: "Seu Web-site" %>

  <%= edit_user.text_field :facebook, placeholder: "Facebook" %>
  <br><br>

  <%= edit_user.label :cover, "Trocar de foto" %>
  <%= edit_user.file_field :cover %><br>

  <%= edit_user.submit "Salvar edições", :class => "btn btn-primary btn-more" %>
<% end %>

app/views/user/new.html.erb
<ul>
<% show_errors(@user).each do |error| %>
    <li><%= error %></li>
<% end %>
</ul>

<%= form_for @user, :class => "form-horizontal", url: new_user_path do |new_user| %>
	<h1>Novo aqui?</h1><br><br>

	<%= new_user.text_field :name, placeholder: "Nome" %><br>

	<%= new_user.text_field :email, placeholder: "E-mail" %><br>

	<%= new_user.password_field :password, placeholder: "Senha" %><br>

	<%= new_user.password_field :password_confirmation, placeholder: "Confirmar senha" %><br>
	<br>
	<%= label_tag "Mande uma foto" %>
	<%= new_user.file_field :cover %><br>

	<%= new_user.submit "Cadastrar usuario", :class => "btn btn-primary btn-more" %>
<% end %>

app/views/user/show.html.erb
<div id="body" style="top: 100px; padding: 60px; padding-top: 0; background: transparent;">

  <h1 id="user_perfil">
    <%= image_tag @user.cover(:medium), style: "width:125px; height:125px; border-radius: 200px; border: 2px solid rgba(0,0,0,0.5); padding: 2px; position:relative;background-color: rgb(200,200,200); float: left;" %>
    <spawn class="name_user_perfil"><%= @user.name %></spawn>
  </h1>

  <div class="data row">

    <div class="col-xs-12 col-ms-4 col-md-4">
      <h3>Minha descrisão:</h3>
      <p><%= @user.description %></p>
    </div>
      
    <div class="col-xs-12 col-ms-4 col-md-4">
      <h3>Opiniões:</h3>
        <% show_opinion %>
        <p>
          <%= link_to (image_tag 'like_icon.png', id: 'icon'), like_like_path(@user.id) %>
          <%= @like %>

          <%= link_to (image_tag 'unlike_icon.png', id: 'icon'), like_nlike_path(@user.id) %>
          <%= @nlike %>
        </p>
      
    </div>

    <div class="col-xs-12 col-ms-4 col-md-4">
      <h3>Web-site:</h3>
      <p><%= @user.web %></p>    
    </div>

    <div class="col-xs-12 col-ms-4 col-md-4">
      <h3>Facebook:</h3>
      <p><%= @user.facebook %></p>
    </div>

   <div class="col-xs-12 col-ms-4 col-md-4">
      <h3>E-mail: </h3>
      <p><%= @user.email %></p>
    </div>

    <div class="col-xs-12 col-ms-4 col-md-4">
      <h3>Conhecimentos:</h3>
      <p><%= @user.acquiriments %></p>
    </div>

    <div class="col-xs-12 col-ms-4 col-md-4">
      <h3>Ideias:</h3>
        <% @ideas.each do |ideas| %>
          <li>
            <%= link_to ideas.title, show_idea_path(ideas.id) %>
          </li>
        <% end %>
    </div>

  </div><br>
  <br>

  

</div>